start-jsk/rtmros_tutorials

hrpsys_ros_bridge_tutorials/catkin.cmake

これに関連すると思います。 すべての問題が解決されたか確認できますか？ @orikuma
https://github.com/start-jsk/rtmros_tutorials/issues/84

fix makefile

---

hrpsys_ros_bridge_tutorials/catkin.cmake
hrpsys_ros_bridge_tutorials/test/hrpsys-samples/hrp4r-virtual-force-sensor.l
hrpsys_ros_bridge_tutorials/test/hrpsys-samples/samplerobot-auto-balancer.l
hrpsys_ros_bridge_tutorials/test/hrpsys-samples/samplerobot-collision-detector.l
hrpsys_ros_bridge_tutorials/test/hrpsys-samples/samplerobot-impedance-controller.l

Update latest hrpsys samples

---

hrpsys_ros_bridge_tutorials/euslisp/make-joint-min-max-table.l

Make limit table to conf only if Euslisp min-max-table exists..

Make limit table to conf only if Euslisp min-max-table exists.

---

hrpsys_ros_bridge_tutorials/catkin.cmake
hrpsys_ros_bridge_tutorials/models/STARO.urdf.xacro
hrpsys_ros_bridge_tutorials/models/gen_hand_attached_staro_model.sh
hrpsys_ros_bridge_tutorials/models/gen_sensor_attached_staro_model.sh
hrpsys_ros_bridge_tutorials/models/staro.yaml

staroモデルでキャリブレーションするために、multisenseモデルがついたurdfを生成するようにしました。

update staro model

---

hrpsys_ros_bridge_tutorials/catkin.cmake
hrpsys_ros_bridge_tutorials/euslisp/ystleg-interface.l
hrpsys_ros_bridge_tutorials/models/ystleg.yaml

Add ystleg compile

---

hrpsys_ros_bridge_tutorials/models/hrp2w.yaml

Fix joint order for hrp2w.yaml

Fix joint order for hrp2w.yaml

---

hrpsys_ros_bridge_tutorials/models/HRP2JSKNTS.urdf.xacro
hrpsys_ros_bridge_tutorials/models/hrp2jsknts.yaml

[hrpsys_ros_bridge_tutorials] Add multisense model to HRP2JSKNTS

---

hrpsys_ros_bridge_tutorials/catkin.cmake

Update hrp2 robots dt;; 0.005->0.004[s]

Update hrp2 robots dt;; 0.005->0.004[s]

---

hrpsys_ros_bridge_tutorials/test/test-walk-check.l

Add check program for walking commands.
(typically, it is used for real robot checking)

Add check program for walking commands

---

hrpsys_ros_bridge_tutorials/test/test-walk-check.l

Increase stride of test walk

---

hrpsys_ros_bridge_tutorials/euslisp/staro-interface.l
hrpsys_ros_bridge_tutorials/euslisp/staro-utils.l

内部リポジトリのstaro-interfaceとstaro-utilsの現在使われているバージョンを追加しました.
#116 から実機用デスクトップに一部追記があったことと, robotiqまわりの仕様が変わっているため,
#116 とは別にPRを出しています.
@snozawa さん, @eisoku9618 さん確認おねがいします.

Add staro-interface and staro-utils

---

hrpsys_ros_bridge_tutorials/models/jaxon.yaml

Update jaxon joint order

---

hrpsys_ros_bridge_tutorials/catkin.cmake

Add toe joint ee setting to hrpsys conf.
Comment out by default (do not change HRP2JSKNT and HRP2JSKNTS behaviour).

Add toe joint ee setting to hrpsys conf. Comment out by default

---

hrpsys_ros_bridge_tutorials/euslisp/jaxon-interface.l

Add jaxon interface

---

hrpsys_ros_bridge_tutorials/catkin.cmake

Fix jaxon ee order (ee order = fsensor order)

Fix jaxon ee order

---

hrpsys_ros_bridge_tutorials/models/jaxon.yaml

[JAXON] fix jaxon.yaml

---

hrpsys_ros_bridge_tutorials/catkin.cmake

Fix jaxon initial pose to avoid leg and hand collision

Fix jaxon initial pose to avoid leg and hand collision

---

hrpsys_ros_bridge_tutorials/catkin.cmake
hrpsys_ros_bridge_tutorials/euslisp/make-joint-min-max-table.l

Update mmtable functions and documents.

Update mmtable functions

---

hrpsys_ros_bridge_tutorials/euslisp/hrp2jsknt-interface.l

Add limb-controller for hrp2jsknt

[hrpsys_ros_bridge_tutorials] Add limb-controller to hrp2jsknt

---

.rosinstall
.travis.yml
hrpsys_ros_bridge_tutorials/catkin.cmake
hrpsys_ros_bridge_tutorials/package.xml

- [hrpsys_ros_bridge_tutorials] use hrp2_models_MODEL_DIR instad of ENV{CVSDIR}/OpenHRP/etc
- [hrpsys_ros_bridge_tutorials/package.xml] fix description
- [hrpsys_ros_bridge_tutorials/package.xml] add hrp2_models to depend

use hrp2_models package

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt
hrpsys_ros_bridge_tutorials/euslisp/make-joint-min-max-table.l

do not merge yet
try https://github.com/jsk-ros-pkg/trans_system/issues/112#issuecomment-88516308 and enable min max for staro

Apply min max

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt

[hrpsys_ros_bridge_tutorials/CMakeLists.txt] revert wrong commit by #219

---

hrpsys_ros_bridge_tutorials/models/jaxon.yaml

see https://github.com/start-jsk/rtmros_tutorials/issues/233

fix joint name

---

hrpsys_gazebo_tutorials/euslisp/hand-command-publisher.l

To use robotiq hand with staro in gazebo, fixed consistency in command and publisher in l/r correspondance

Modified l/r correspondance which was inconsistent in hand-commadn-publisher.l

---

hrpsys_ros_bridge_tutorials/euslisp/jaxon-interface.l

modify the number of ")" in jaxon-interface.l

modify the number of parenthesis

---

hrpsys_ros_bridge_tutorials/test/test-kf-st-check.l
hrpsys_ros_bridge_tutorials/test/test-walk-check.l

Update euslisp st abc kf checks.

Update euslisp st abc kf checks

---

hrpsys_ros_bridge_tutorials/models/jaxon.yaml

add definition of transformation for prosilica and fisheye

add fisheye transformation in jaxon.yaml

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt
hrpsys_ros_bridge_tutorials/models/staro.yaml

https://github.com/start-jsk/rtmros_tutorials/pull/260 から移しました．

add jsk foot end-coords

---

hrpsys_ros_bridge_tutorials/models/jaxon.yaml

[hrpsys_ros_bridge_tutorials] fix jaxon fisheye config

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt
hrpsys_ros_bridge_tutorials/test/test-robot-model.l
hrpsys_ros_bridge_tutorials/test/test_robot_model.launch

https://github.com/k-okada/rtmros_tutorials/pull/1
@eisoku9618 やりたかったのはこれかな？

fix link shape for min-max problem?

---

hrpsys_ros_bridge_tutorials/models/hrp2jsknt.yaml
hrpsys_ros_bridge_tutorials/models/hrp2jsknts.yaml

add tf "fisheye" for chest camera to hrp2jsknt and hrp2jsknts models

add fisheye tf to hrp2jsknt and hrp2jsknts

---

hrpsys_ros_bridge_tutorials/models/hrp2jsknt.yaml
hrpsys_ros_bridge_tutorials/models/hrp2jsknts.yaml

fisheye frame_id change for look-at and fisheye ray

change fisheye frame_id rotation for look-at

---

hrpsys_ros_bridge_tutorials/models/jaxon.yaml

jaxon fisheye is also changed for look-at

change jaxon fisheye rotation

---

hrpsys_ros_bridge_tutorials/models/jaxon.yaml

JAXONが履いているKAWADA足はゴム靴＋緑色の接着剤がついているので，+4mmしました．

add rubber shoes and green bonding

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/hrp2_hrpsys_config.py

Move hrp2_hrpsys_config functions from jsk_hrp2_setup.

Move hrp2_hrpsys_config functions from jsk_hrp2_setup

---

hrpsys_ros_bridge_tutorials/euslisp/jaxon_red-interface.l

https://github.com/start-jsk/rtmros_tutorials/commit/33b5fc5e2627329349f6961cab216eaf3d980a08 で空ファイルをコミットしていたみたいなので，直しました．

add jaxon_red interface

---

hrpsys_gazebo_tutorials/launch/gazebo_jaxon_no_controllers.launch
hrpsys_gazebo_tutorials/launch/gazebo_jaxon_no_controllers_drc_testbed.launch

[hrpsys_gazebo_tutorials] add launch that enables hokuyo of multisense

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt
hrpsys_ros_bridge_tutorials/models/hrp2jsknt.yaml

Update for karasawa sole plate for hrp2jsknt.

Update for karasawa sole plate for hrp2jsknt

---

hrpsys_ros_bridge_tutorials/euslisp/make-joint-min-max-table.l

Generate hrp2jsknt ankle mm table.

Generate hrp2jsknt ankle mm table

---

hrpsys_ros_bridge_tutorials/euslisp/make-joint-min-max-table.l

!! DO NOT MERGE YET !!
Add mmtable for hrp2jsknts.

Add mmtable for hrp2jsknts

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/hrp2_hrpsys_config.py

Add kf offset for hrp2jsknts

---

hrpsys_ros_bridge_tutorials/euslisp/jaxon-interface.l
hrpsys_ros_bridge_tutorials/euslisp/jaxon_red-interface.l

jaxon for serious network problem

[hrpsys_ros_bridge_tutorials] Use :controller-timeout nil as default for

---

hrpsys_gazebo_tutorials/config/JAXON.yaml
hrpsys_gazebo_tutorials/robot_models/JAXON/JAXON.urdf.xacro
hrpsys_gazebo_tutorials/robot_models/JAXON/JAXON_without_multisense.urdf.xacro

JAXONで力センサのシミュレーションが動いていなかったので動くようにしました．

use force sensor simulation in JAXON

---

hrpsys_ros_bridge_tutorials/test/hrpsys-samples/samplerobot-auto-balancer.l

Update auto balancer euslisp sample

Update auto balancer euslisp sample

---

hrpsys_ros_bridge_tutorials/test/hrpsys-samples/samplerobot-auto-balancer.l

Add change step param sample.
@Tnoriaki

Add change step param sample

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/hrp2_hrpsys_config.py

Update hrp2 config parameters. Remove unnecessary parameters and move real robot seting to jsk_hrp2_ros_bridge
Use eefm -> eefmqp st.

Update hrp2 config parameters.

---

hrpsys_gazebo_tutorials/robot_models/SampleRobot/SampleRobot.urdf.xacro

https://github.com/start-jsk/rtmros_gazebo/issues/191
が修正されたかと思います。

update imu pose

---

hrpsys_gazebo_tutorials/launch/hrp2jsk_hrpsys_bringup.launch
hrpsys_gazebo_tutorials/launch/hrp2jsknt_hrpsys_bringup.launch
hrpsys_gazebo_tutorials/launch/hrp2jsknts_hrpsys_bringup.launch
hrpsys_gazebo_tutorials/launch/jaxon_hrpsys_bringup.launch
hrpsys_gazebo_tutorials/launch/staro_hrpsys_bringup.launch

Please merge after https://github.com/start-jsk/rtmros_gazebo/pull/189

use hrpys_py

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt

https://github.com/start-jsk/rtmros_hrp2/pull/243

ignore JAXON_RED when using travis

---

hrpsys_gazebo_tutorials/config/HRP2JSK.yaml
hrpsys_gazebo_tutorials/config/HRP2JSKNT.yaml
hrpsys_gazebo_tutorials/config/HRP2JSKNTS.yaml
hrpsys_gazebo_tutorials/config/HRP3HAND_L.yaml
hrpsys_gazebo_tutorials/config/HRP3HAND_R.yaml
hrpsys_gazebo_tutorials/config/JAXON.yaml
hrpsys_gazebo_tutorials/config/STARO.yaml
hrpsys_gazebo_tutorials/config/SampleRobot.yaml
hrpsys_gazebo_tutorials/launch/hrp4c_hrpsys_bringup.launch
hrpsys_gazebo_tutorials/launch/jaxon_hrpsys_bringup.launch

add loose synchoronized setting and rate of iob
For new robot, default config file is added. see https://github.com/start-jsk/rtmros_gazebo/pull/200

update config and launch file

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt
hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/samplerobot_hrpsys_config.py

Update samplerobot conf and hrpsys_config

Update samplerobot conf and hrpsys_configb

---

hrpsys_ros_bridge_tutorials/euslisp/hrp2jsk-interface.l

Added methods :start-grasp and :stop-grasp for hrp2jsk-interface

Add hrp2jsk-interface methods :start-grasp and :stop-grasp

---

hrpsys_ros_bridge_tutorials/euslisp/hrp2jsknt-utils.l

@mmurooka さんのdemoプログラムから持って来ました．

Add additional end coords

---

hrpsys_ros_bridge_tutorials/test/hrpsys-samples/samplerobot-auto-balancer.l

Update set footstep samples

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/urata_hrpsys_config.py

Increase jaxon xy force damping gain to reduce ocsilation

Increase jaxon xy force damping gain to reduce ocsilation

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt

fix with https://github.com/start-jsk/rtmros_hrp2/pull/264

Fix JAXON RED hand model

---

hrpsys_ros_bridge_tutorials/euslisp/jaxon_red-interface.l

実機のときと、シミュレーションの時で異なるハンドコントローラを使うようにしました。

use jvrc-hand at JAXON_RED while using simulation

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/hrp2_hrpsys_config.py
hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/urata_hrpsys_config.py

Update st limb gain parameters

Update st limb gain parameters

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt
hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/urata_hrpsys_config.py
hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/urataleg_hrpsys_config.py

Use robot hrpsys config for urataleg

Use robot hrpsys config for urataleg

---

hrpsys_gazebo_tutorials/config/HRP2JSK.yaml
hrpsys_gazebo_tutorials/config/HRP2JSKNT.yaml
hrpsys_gazebo_tutorials/config/HRP2JSKNTS.yaml

Fix iob_rate to 250 because dt is 0.004[s] for HRP2 robots.
@YoheiKakiuchi ,
could you check this?

Fix iob_rate to 250 <= dt = 0.004[s]

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt
hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/urata_hrpsys_config.py
hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/ystleg_hrpsys_config.py

Update ystleg setting.
@YuyaNagamatsu
please check this after merging.

Update ystleg setting

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt

Fix for dependency of urdf file.
Directly depends on urdf custom target instead of urdf file itself.

Fix for dependency of urdf file

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt

Update pdgain file conf name

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/hrp2_hrpsys_config.py

Add emergency stopper setting for hrp2.

Add emergency stopper setting for hrp2.

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/hrp2_hrpsys_config.py

Update hrp2 st params for vertices

Update hrp2 st params for vertices

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/chidori_hrpsys_config.py

add chidori_hrpsys_config.py but st's and gaitgenerator's parameters are not changed

add chidori_hrpsys_config.py

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/chidori_hrpsys_config.py

Update chidori st params.

---

hrpsys_ros_bridge_tutorials/euslisp/hrp2jsk-interface.l
hrpsys_ros_bridge_tutorials/euslisp/hrp2w-interface.l

Use grasp controller methods in rtm-ros-robot-interface.l

Use grasp controller methods in rtm-ros-robot-interface.l

---

hrpsys_ros_bridge_tutorials/euslisp/hrp3hand-utils.l
hrpsys_ros_bridge_tutorials/models/hrp3hand_l.yaml
hrpsys_ros_bridge_tutorials/models/hrp3hand_r.yaml

Update hrp3hand methods

---

hrpsys_ros_bridge_tutorials/euslisp/hrp3hand-utils.l

Add hrp3hand new pose.

---

hrpsys_ros_bridge_tutorials/euslisp/hrp2-common-interface.l

Add hand state method.

---

hrpsys_ros_bridge_tutorials/euslisp/jaxon-utils.l
hrpsys_ros_bridge_tutorials/euslisp/jaxon_red-utils.l
hrpsys_ros_bridge_tutorials/euslisp/thkhand-utils.l

Add thk hand eusmodel to commonize interface.

Add thk hand eusmodel to commonize interface

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/urata_hrpsys_config.py

空中に釣っている時に足平が地面と水平となる姿勢になるボタンをdashboardに追加したかったので，hcfにその姿勢を定義しました．

[hrpsys_ros_bridge] add jaxonResetLandingPose for dashboard

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/hrp2_hrpsys_config.py

modify cp_check_margin for hrp2

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/urata_hrpsys_config.py

Modified st parameters for JAXON1 by @snozawa and @orikuma

modify jaxon1 st parameters by snozawa san and orikuma san

---

hrpsys_ros_bridge_tutorials/euslisp/thkhand-utils.l

Add getter method for hand joint

Add getter method for hand joint

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/urata_hrpsys_config.py

レプトリノ足のパラメータにしました．
体内も今このbranchになっています．

Update jaxon foot parameter by reptrino

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/urata_hrpsys_config.py

https://github.com/start-jsk/rtmros_tutorials/pull/439#issuecomment-159855205

[hrpsys_ros_bridge_tutorials] Enable emergency stopper for JAXON

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/hrp2_hrpsys_config.py

https://github.com/fkanehiro/hrpsys-base/pull/889 の変更に合わせてパラメータを変更しました．

update default parameter for estop

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt
hrpsys_ros_bridge_tutorials/models/jaxon.yaml

[hrpsys_ros_bridge_tutorials] use leptrino foot in jaxon1

---

hrpsys_ros_bridge_tutorials/euslisp/jaxon-common-interface.l
hrpsys_ros_bridge_tutorials/euslisp/jaxon-interface.l
hrpsys_ros_bridge_tutorials/euslisp/jaxon_red-interface.l

Add jaxon-common-interface.l for common parts of jaxon-interface.l and jaxon_red-interface.l.
Use jaxon-common-interface class from jaxon and jaxon_red.

Add jaxon-common-interface.l

---

hrpsys_ros_bridge_tutorials/euslisp/chidori-interface.l
hrpsys_ros_bridge_tutorials/euslisp/hrp2jsk-interface.l
hrpsys_ros_bridge_tutorials/euslisp/hrp2jsknt-interface.l
hrpsys_ros_bridge_tutorials/euslisp/hrp2jsknts-interface.l
hrpsys_ros_bridge_tutorials/euslisp/hrp2w-interface.l
hrpsys_ros_bridge_tutorials/euslisp/jaxon-common-interface.l
hrpsys_ros_bridge_tutorials/euslisp/urataleg-interface.l

Use :def-limb-controller-method for robots.

Use :def-limb-controller-method for robots.

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/urata_hrpsys_config.py

Set moment_limit for jaxon and jaxon_red ST.
80Nmでのリミットは確認してますが，90Nmにしてみました．実機確認はあとで．
また，ロール方向モーメントのリミットはいらないのかも．

Set moment_limit for jaxon and jaxon_red ST.

---

hrpsys_ros_bridge_tutorials/models/HRP2JSK.urdf.xacro

Related with https://github.com/start-jsk/rtmros_hrp2/pull/354

[hrpsys_ros_bridge_tutorials/models/HRP2JSK.urdf.xacro] Update hrp2007 multisense model

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt

Add YSTLEG seq optionaldata setting.
@YuyaNagamatsu

Add YSTLEG seq optionaldata setting

---

hrpsys_ros_bridge_tutorials/euslisp/hrp2jsknt-utils.l
hrpsys_ros_bridge_tutorials/euslisp/make-joint-min-max-table.l

Add defmmtable.
Use it ini :init-ending of hrp2jsknt.

Add defmmtable for hrp2jsknt

---

hrpsys_ros_bridge_tutorials/models/HRP2JSKNTS.urdf.xacro
hrpsys_ros_bridge_tutorials/models/hrp2jsknts.yaml

changed camera from multisense -> carmine
(thanks to @mmurooka )

[hrp2jsknts] change camera model to carmine

---

hrpsys_ros_bridge_tutorials/euslisp/make-joint-min-max-table.l
hrpsys_ros_bridge_tutorials/models/hrp2jsk.yaml

Revert ankle spacer for HRP2JSK. Revert end-coords and min-max table generation.
https://github.com/start-jsk/rtmros_hrp2/pull/388

Revert ankle spacer for HRP2JSK. Revert end-coords and min-max table generation.

---

hrpsys_ros_bridge_tutorials/euslisp/make-joint-min-max-table.l

Revert hrp2jsknt ankle min max table generation.

Revert hrp2jsknt ankle min max table generation.

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt

Use HRP2JSK original end_effector conf setting without ankle spacer

Use HRP2JSK original end_effector conf setting without ankle spacer

---

hrpsys_ros_bridge_tutorials/package.xml

Add robot-init setting for hrp2 and jsk robots according to https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/222.
Please merge after https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/222

Add robot-init setting for hrp2 and jsk robots

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt

Do not write direct path for vrml models and use rospack find for it.

Do not write direct path for vrml models and use rospack find for it.

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt
hrpsys_ros_bridge_tutorials/euslisp/tqleg0-interface.l
hrpsys_ros_bridge_tutorials/models/tqleg0.yaml
hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/tqleg0_hrpsys_config.py
hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/urata_hrpsys_config.py

TQLEG0(足首トルクセンサ付き12自由度YSTLEG)モデルです。
commit 2/3
1. jsk_models
2. hrpsys_ros_bridge_tutorials
3. VSProjects (trans_systemのうちfsharpのみ)

add and initialize TQLEG0 interface

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt
hrpsys_ros_bridge_tutorials/models/HRP2W.urdf.xacro

Add HRP2W with multisense model and Update CMakeLists.txt.

[hrpsys_ros_bridge_tutorials] Update HRP2W model with multisenseS7

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt
hrpsys_ros_bridge_tutorials/euslisp/hrp2w_mbzirc-interface.l
hrpsys_ros_bridge_tutorials/euslisp/hrp2w_mbzirc-utils.l
hrpsys_ros_bridge_tutorials/models/HRP2W_MBZIRC.urdf.xacro
hrpsys_ros_bridge_tutorials/models/hrp2w_mbzirc.yaml
hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/hrp2_hrpsys_config.py
hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/hrp2w_mbzirc_hrpsys_config.py

Added urdf models and euslisp interface for HRP2W_MBZIRC

[hrpsys_ros_bridge_tutorials] Add HRP2W_MBZIRC urdf and euslisp interface

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/hrp2_hrpsys_config.py

Update hrp2016 and hrp2007 st algorithm.
(commit local change in hrp2016 and hrp2007)

Update hrp2016 and hrp2007 st algorithm

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/urata_hrpsys_config.py

クレーンを使った着地が荒いのでCHIDORIのLandingPoseを追加しました．
実機で動作確認済みです．

add chidoriResetLandingPose

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/urata_hrpsys_config.py

Local change in jaxon_red since Jan 2016

update jaxon st algorithm

---

hrpsys_ros_bridge_tutorials/test/test-walk-check.l

Add test to walk backward by large stride

Add test to walk backward by large stride

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/hrp2_hrpsys_config.py

Use swing damping for hrp2017

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/urata_hrpsys_config.py

Use swing damping and modification for jaxon

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/urata_hrpsys_config.py

modify ST param for CHIDORI according to the correct COM height

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/hrp2_hrpsys_config.py

Use hrp2017c swing foot modif

---

hrpsys_ros_bridge_tutorials/test/test-walk-check.l

Fix test-walk-bwd function name

[hrpsys_ros_bridge_tutorials/test] Fix function name for test-walk-check

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/hrp2_hrpsys_config.py

Update st params for swing foot.
Fix order of definition for hrp2016 and hrp2007 (<= this do not change behavior)
Use swing damping and swing foot compensation.

Update st params

---

hrpsys_ros_bridge_tutorials/package.xml

roseus_msgs is no logner rquried

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt

SequencePlayerでoptional dataを送るための設定です

add optional data conf for CHIDORI

---

hrpsys_ros_bridge_tutorials/test/test-all-robots-check.l

Add test code to check min/max table validity to check #508.
How to execute and results.
```
roseus test/test-all-robots-check.l 
TEST-NAME: test-model-gen
now testing...
start testing [test-model-gen]                                                                                                                                                                                                                                                          
;; extending gcstack 0x698eee0[32738] --> 0x736a620[65476] top=7d3f
;; HRP2JSK done
;; HRP2JSKNT done
;; HRP2JSKNTS done
;; HRP2W done
;; HRP2G done
;; URATALEG done
;; extending gcstack 0x736a620[65466] --> 0x14380180[130932] top=6f40
;; could not find pacakge [thk_hand_controller] …
```

Add test code to check min/max table validity

---

.travis.yml

test is failed
```
+++sudo apt-get install -y -q -qq python-rosdep python-pip python-wstool python-catkin-tools ros-hydro-rosbash ros-hydro-rospack
E: Unable to locate package ros-hydro-rosbash
E: Unable to locate package ros-hydro-rospack
```
https://github.com/start-jsk/rtmros_tutorials/pull/532

update .travis and using indigo for test

---

hrpsys_gazebo_tutorials/config/HRP2JSK.yaml
hrpsys_gazebo_tutorials/config/HRP2JSKNT.yaml
hrpsys_gazebo_tutorials/config/HRP2JSKNTS.yaml

I performed gain tuning for HRP2 walk.

[hrpsys_gazebo_tutorials] gain tuning for HRP2

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt
hrpsys_ros_bridge_tutorials/euslisp/a0b-interface.l
hrpsys_ros_bridge_tutorials/models/a0b.yaml
hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/a0b_hrpsys_config.py
hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/urata_hrpsys_config.py

https://github.com/start-jsk/rtmros_hrp2/pull/602
で追加したA0Bモデルに対応するインタフェースです．

[hrpsys_ros_bridge_tutorials/A0B] add A0B interface

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt
hrpsys_ros_bridge_tutorials/scripts/add-obj-to-hrpproject.py
hrpsys_ros_bridge_tutorials/scripts/publish_end_effector_tf.py
hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/hrp2_hrpsys_config.py
hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/samplerobot_hrpsys_config.py
hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/urata_hrpsys_config.py

fix cmake and python3 problems. `catkin build hrpsys_ros_bridge_tutorials` has passed successfully.
- python2 to 3
- `xacro.py` is deprecated in Noetic
- https://github.com/Naoki-Hiraoka/multisense_ros/tree/3.4.9_fixed is needed

[hrpsys_ros_bridge_tutorials] fix for Noetic
