start-jsk/rtmros_tutorials

hrpsys_ros_bridge_tutorials/euslisp/make-joint-min-max-table.l

Add legs' crotch-y min max table for hrp2jsk robots to avoid self collision.

Add legs' crotch-y min max table for hrp2jsk robots

---

hrpsys_ros_bridge_tutorials/catkin.cmake
hrpsys_ros_bridge_tutorials/models/gen_hand_attached_hrp2_model.sh
hrpsys_ros_bridge_tutorials/models/gen_hand_attached_staro_model.sh

1. Do not allow parallel execution of export_collada and rostest
* update compile_robot_model.cmake [https://github.com/start-jsk/rtmros_common/pull/643]
* add set(compile_robots ${compile_robots} PARENT_SCOPE) to the macros in order to make the variable __global__
2. Use [euscollada/remove_sensor_from_urdf.py](https://github.com/jsk-ros-pkg/jsk_model_tools/pull/92) to remove link from urdf. I don't know why but we cannot use pipe on `catkin build` on many CPUs. It means a lot of **sed hacks** are not allowed.

Fix model generation for catkin tools

---

hrpsys_ros_bridge_tutorials/models/staro.yaml

End-coords of straight-version robotiq hand attachment was wrong in  staro.yaml (This was same as angled-version).

Modify staro robotiq straight end coords

---

hrpsys_ros_bridge_tutorials/catkin.cmake

https://github.com/start-jsk/rtmros_tutorials/pull/195 のend-effectorの値が若干違う気がしますが，どうでしょうか？
※PRへのPRの方法が分かりませんでした．．．
```lisp
1.irteusgl$ (setq *robot* (jaxon))
#<jaxon-robot #X5620330 JAXON  0.0 0.0 0.0 / 0.0 0.0 0.0>
2.irteusgl$ (print-end-effector-parameter-conf-from-robot *robot*)
end_effectors: rarm,RARM_JOINT7,CHEST_JOINT2,-0.055,0.0,-0.237,-0.57735,0.57735,0.57735,2.0944, larm,LARM_JOINT7,CHEST_JOINT2,-0.055,0.0,-0.237,0.57735,0.57735,-0.57735,2.0944, rleg,RLEG_JOINT5,WAIST,0.0,0.0,-0.096,0.0,0.0,0.0,0.0, lleg,LLEG_JOINT5,WAIST,0.0,0.0,-0.096,0.0,0.0,0.0,0.0,
nil
```

Fix update jaxon

---

hrpsys_ros_bridge_tutorials/euslisp/staro-utils.l

As support polygon methods were added to irteus by @snozawa at https://github.com/euslisp/jskeus/pull/177, so I deleted the definition of contact-polygons method of staro-utils.l.

Delete definition of contact-polygons method

---

hrpsys_ros_bridge_tutorials/euslisp/jaxon-interface.l

related to https://github.com/jsk-ros-pkg/trans_system/pull/124 .
Add jaxon-interface methods for thk hand in jaxon-interface.l .
This change does not make error even if thk_hand_controller package is not installed.
Also, this change does not make error even if jaxon in hrpsys-simulator does not have thk hand.

[hrpsys_ros_bridge_tutorials] add method definition for jaxon thk hand

---

hrpsys_gazebo_tutorials/robot_models/JAXON/JAXON_without_multisense.urdf.xacro

JAXON_without_multisense を使っていると left_camera_optical_frame みたいなTFがありませんという
エラーになってこれでエラーがなくなります．

[hrpsys_gazebo_tutorials] add multisense urdf of real robot to jaxon_without_multisense xacro

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt
hrpsys_ros_bridge_tutorials/models/hrp2jsknts.yaml

まだマージしないでください。
https://github.com/start-jsk/rtmros_hrp2/pull/157
に対応して、唐澤君あしうらパーツの変更です。
あしうらパーツの分、end-coordsを下げました。

Fix for karasawa sole plate for hrp2jsknts

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt
hrpsys_ros_bridge_tutorials/models/HRP2JSK.urdf.xacro

Fix parallel compile of hrpsys_ros_bridge_tutorials.
This is intended to solve https://github.com/start-jsk/rtmros_common/pull/754.
Previously, catkin build of hrpsys_ros_bridge_tutorials sometimes successes and failes. 
I checked catkin build many times:
```
roscd hrpsys_ros_bridge_tutorials
SUCCESSNUM=0;NUM=0;while [ $NUM -lt 50 ]; do git clean -xfd . && catkin bt --force-cmake --start-with-this && SUCCESSNUM=`expr $SUCCESSNUM + 1`; NUM=`expr $NUM + 1`;done; echo "SUCCESS $SUCCESSNUM / $NUM"
```
After this PR, I'd like to check rtmros_common and rtmros_hrp2 master branch build.

Fix parallel compile of hrpsys_ros_bridge_tutorials

---

hrpsys_ros_bridge_tutorials/euslisp/make-joint-min-max-table.l

逆そり防止のマージンですが、jaxon_redのモデル修正にともない、問題なさそうなので変更します。
see: https://github.com/start-jsk/rtmros_hrp2/pull/243

update min-max-table margin of JAXON waist-p joint

---

hrpsys_ros_bridge_tutorials/euslisp/jaxon-utils.l
hrpsys_ros_bridge_tutorials/euslisp/jaxon_red-utils.l

接触可能と思われる部分のcascaded-coordsが欲しかったので，staro-utils.lのように，追加して見ました．
```lisp
(progn
(send (send *robot* :get :rhand-contact-coords) :draw-on :flush t :size 200 :color #f(1 0 0) :width 5)
(send (send *robot* :get :lhand-contact-coords) :draw-on :flush t :size 200 :color #f(1 0 0) :width 5)
(send (send *robot* :get :rarm-wrist-contact-coords) :draw-on :flush t :size 200 :color #f(0 1 0) :width 5)
(send (send *robot* :get :larm-wrist-contact-coords) :draw-on :flush t :size 200 :color #f(0 1 0) :width 5)
(send (send *robot* :get :rleg-thin-contact-coords) :draw-on :flush t :size 200 :color #f(0 0 1) :width 5)
(send (send *robot* :get :lleg-thin-contact-coords) :draw-on :flush t :size 200 :color #f(0 0 1) :width 5)
)
```
これがあると以下のような姿勢を作るときに便利そうです．

add jaxon-utils

---

hrpsys_ros_bridge_tutorials/test/hrpsys-samples/samplerobot-auto-balancer.l

Add footstep overwrite sample while walking.
Currently, `:set-foot-steps` is used for this.
@garaemon 
Please see this example if https://github.com/fkanehiro/hrpsys-base/pull/720 is merged.

Add footstep overwrite sample

---

hrpsys_gazebo_tutorials/config/HRP2JSKNT.yaml
hrpsys_gazebo_tutorials/config/HRP2JSKNTS.yaml
hrpsys_ros_bridge_tutorials/models/hrp2jsk.yaml
hrpsys_ros_bridge_tutorials/models/hrp2jsknt.yaml
hrpsys_ros_bridge_tutorials/models/hrp2jsknts.yaml
hrpsys_ros_bridge_tutorials/models/jaxon.yaml
hrpsys_ros_bridge_tutorials/models/staro.yaml

1. Add missing specification about xml replacement rule for gazebo model
2. Fix syntax of staro yaml
3. Fix the number of joints controlled via hrpsys because now robot and
hands are integrated into one robot model

[hrpsys_ros_bridge_tutorials, hrpsys_gazebo_tutorials] Fix for gazebo simulation.

---

hrpsys_gazebo_tutorials/robot_models/JAXON/JAXON.urdf.xacro
hrpsys_ros_bridge_tutorials/models/jaxon.yaml

JAXON実機のurdfをgazebo上で使うためのurdf側の変更です. https://github.com/jsk-ros-pkg/trans_system/pull/454 が必要です.
ひとまずはJAXONのみの変更になっています.
変更点は以下です.
1. gazebo用urdf内でのpluginのload
gazeboでloadされるurdfにmultisense関連のpluginを記述しました.
内容はmultisense_sl_v4.urdfを参考にしています.
https://github.com/jsk-ros-pkg/trans_system/pull/454 のJskMultisenseSLPluginを使用しています.
2. multisense関連のリンク定義の変更
gazeboではリンクにinertialタグがないと有効なリンクとみなされないようなので, inertialタグを追加しました. 値はleft_optical_frameの値を参考にしています.
cf. http://gazebosim.org/tutorials/?tut=ros_urdf
3. multisense関連の関節定義の変更
元のurdfではleft_camera_optical_frame -> motor -> spindle -> hokuyo_linkの間の座標変換が定義されていないため, gazeboで元のモデルを表示するとleft_camera_optical_frameにhokuyo_linkが埋まります.
実機ではこの座標変換はmultisense_driverがtfとして出していますが, gazebo上ではtfに加えてgazebo内でのリンク位置を決めるための座標が必要になります. …

Jaxon in gazebo using real urdf model

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt

https://github.com/start-jsk/rtmros_tutorials/issues/373
のhotfixなかんじの修正です。
add_custom_targetの指定の仕方が少しちぐはぐなようにみえたので、それを消して
最後のcompile_urdf_robotsのリストのみadd_custom_targetするようにしました。
また、上記リストもdependencyを与えて、並列実行されないようにしました。
```
SUCCESSNUM=0;NUM=0;while [ $NUM -lt 10 ]; do git clean -xfd . && catkin bt --force-cmake --start-with-this && SUCCESSNUM=`expr $SUCCESSNUM + 1`; NUM=`expr $NUM + 1`;done; echo "SUCCESS $SUCCESSNUM / $NUM"
```
でチェックして、
- もともと=>成功率`0/10`
- add_custom_targetを減らす=>成功率`4/10`
- 並列実行にならないようにした（このPR）=>成功率`10/10`
と手元ではなりました。

Define dependency for urdf conversion to avoid parallel cmake problem

---

hrpsys_gazebo_tutorials/robot_models/SampleRobot/SampleRobot.urdf.xacro
hrpsys_ros_bridge_tutorials/CMakeLists.txt
hrpsys_ros_bridge_tutorials/models/samplerobot.yaml

https://github.com/start-jsk/rtmros_tutorials/pull/380 の続きでgazeboのSampleRobotが脱力してしまう問題ですが，
https://github.com/start-jsk/rtmros_tutorials/pull/365 で 関節のtypeをcontinuousからrevoluteに変える変更が引き継がれておらず，
revoluteにするようにしたら解決しました．

Samplerobot wh sensors

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt

Comment out deprecated test using euslisp + samplerobot because latest tests are moved to hrpsys_ros_bridge.

Comment out deprecated test using euslisp + samplerobot because latest tests are moved to hrpsys_ros_bridge

---

hrpsys_ros_bridge_tutorials/euslisp/hrp3hand-utils.l

Fix hrp3hand thumb joint name according to old rbrain definitions.

Fix hrp3hand thumb joint name according to old rbrain definitions.

---

hrpsys_ros_bridge_tutorials/euslisp/jaxon-utils.l
hrpsys_ros_bridge_tutorials/euslisp/jaxon_red-utils.l

腰の高さを含めてikを解きたい時にルートリンクにくっついているend-coordsがあると便利かと思ったので，追加しました．

Add hip contact coords

---

hrpsys_ros_bridge_tutorials/models/JAXON.urdf.xacro

a. Laser pointclouds with caliblated multisense of JAXON. Blue points are within 30mm from the ground plane (based on lleg_end_coords)
b. Stereo pointclouds with caliblated multisense of JAXON.

[hrpsys_ros_bridge_tutorials] Calibrate multisense external parameters of JAXON for new head

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/urata_hrpsys_config.py

浦田脚のautobarancerのデフォルトのパラメータを明示しました．
(CHIDORIよりコピー)
実験中に最初autobarancerをONにしたとき，
default_zmp_offsetsに変な値が入っていたからなのか，そうではなく気のせいだったか，
脚が変な方向に動いたから念のためです．
そのときはdefault_zmp_offsetsをeusから0セットしたら挙動が治りました．

add abc params to setStAbcParametersURATALEG

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/hrp2_hrpsys_config.py

新しい転倒判定方法( https://github.com/fkanehiro/hrpsys-base/pull/857 )では，今の```cp_check_margin``` のデフォルト値では大きすぎるので変更しました．

modify default parameter for hrp2

---

hrpsys_ros_bridge_tutorials/euslisp/jaxon-common-interface.l

Make :get-joint-angle, :get-joint-velocity, :get-joint-effort depreated because these method names are too general.
Accordig to the discussion:https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/190

Add jaxon gripper method

---

hrpsys_ros_bridge_tutorials/euslisp/make-joint-min-max-table.l

Do not gen limit table for HRP2JSKNTS because we remove kawasakisan ankle parts.(https://github.com/start-jsk/rtmros_hrp2/pull/364)

Do not gen limit table for HRP2JSKNTS because we remove kawasakisan ankle parts.(https://github.com/start-jsk/rtmros_hrp2/pull/364)

---

hrpsys_ros_bridge_tutorials/euslisp/hrp2w-interface.l

Check :def-limb-controller-method for backward compatibility for deb-installed hrpsys_ros_bridge.
@wesleypchan

 Check :def-limb-controller-method for backward compatibility for deb-installed hrpsys_ros_bridge.

---

hrpsys_ros_bridge_tutorials/models/JAXON_RED.urdf.xacro

mutlisense mount of JAXON_RED is replaced because its back frame was cut

[hrpsys_ros_bridge_tutorials] caalibrate mutlisense because JAXON_RED mutlisense mount is modified on 2016/05/30

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt

chidoriをchoreonoid上で動かしていた際に、gainの変更ができなかった(変更しようとすると0になる)ので、調べてみたところ、pdgains.file_nameが間違っていたようです。

[hrpsys_ros_bridge_tutorials] fix CMakeLists.txt

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/hrp2_hrpsys_config.py

delayhoffarbibでXYがZより0.1秒はやく収束するようにして、
着地直前に真上から下におろすようにしました。
hrp2017でドアあけ、基本歩行テストなどで確認したので、
全脚型HRP2のパラメタをかえました。
JAXON系は@YutaKojioに確認してもらってます。
問題あればおしえてください。

Update delayhoffarbib swing time parameters. XY convergence is faster than Z for all hrp2 legged robots.

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/urata_hrpsys_config.py

https://github.com/start-jsk/rtmros_hrp2/pull/448
上記のモデル変更で、default_zmp_offsetは設定しなくても、ほぼend-coordsにzmpが来るようになっています。

[JAXON] fix default_zmp_offset for JAXON

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/urata_hrpsys_config.py

Changed default impedance parameter for JAXON referencing DRC's param (https://github.com/jsk-ros-pkg/jsk_demos/blob/master/jsk_2015_06_hrp_drc/drc_task_common/euslisp/robot-util.l#L434-L464)
I verified this parameter with JAXON1 and JAXON2.

change impedance param for jaxon

---

hrpsys_ros_bridge_tutorials/euslisp/hrp4r-utils.l
hrpsys_ros_bridge_tutorials/euslisp/jaxon-utils.l
hrpsys_ros_bridge_tutorials/euslisp/jaxon_red-utils.l
hrpsys_ros_bridge_tutorials/euslisp/staro-utils.l

some robots ignore min-max table by overwriting :init-ending method in -utils.l

[hrpsys_ros_bridge_tutorials] fix for min-max table

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/urata_hrpsys_config.py

modify the following parameters for hrpsys's st and abc of JAXON BLUE
- ST
- damping gain (soften)
- swing leg modification (chaned to not use)
- state feedback gain (modify cog height for only leg)
- foot margine (debug, default not using)
- ABC
- default zmp offset (moved to the center of foot)

[hrpsys_ros_bridge_tutorials] Update JAXON_BLUE hrpsys param

---

hrpsys_ros_bridge_tutorials/euslisp/hrp2jsk-utils.l
hrpsys_ros_bridge_tutorials/euslisp/hrp2jsknt-utils.l
hrpsys_ros_bridge_tutorials/euslisp/hrp2jsknts-utils.l
hrpsys_ros_bridge_tutorials/euslisp/hrp4r-utils.l
hrpsys_ros_bridge_tutorials/euslisp/jaxon-utils.l
hrpsys_ros_bridge_tutorials/euslisp/jaxon_blue-utils.l
hrpsys_ros_bridge_tutorials/euslisp/jaxon_red-utils.l

For backward compatibility, new collada2eus does not translate root link.
This information (robot model to root link) is not in urdf model.

Add offset from model to root link for euscollada/collada2eus_urdfmodel

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt

* JAXONに倣って，footstepのために両足の end-coordsを加えた CHIDORI_SENSORS.urdfを生成するように CMakeListsに書き加えました．
* 現在のchoreonoidのモデルはこのCHIDORI_SENSORS.urdfを使うのをdefaultにしています．

add legs end coords for footstep planning

---

.travis.yml
nextage_tutorials/CMakeLists.txt
nextage_tutorials/config/nextage.rviz
nextage_tutorials/config/nextage.yaml
nextage_tutorials/euslisp/nextage-interface.l
nextage_tutorials/launch/sample.launch
nextage_tutorials/model/NextageKinect.xacro
nextage_tutorials/model/sample.world
nextage_tutorials/package.xml
nextage_tutorials/sample/sample.l

you can use https://gist.github.com/k-okada/94b7140e4c9fbf800f77c506a2ddb8f6 rosinstall file to setup environment
```
$ roslaunch nextage_tutorials sample.launch
$ rosrun nextage_tutorials sample.l
```

add nextage tutorials for euslisp/gazebo users

---

README.md
hrpsys_gazebo_tutorials/config/HRP2JSK.yaml
hrpsys_gazebo_tutorials/config/HRP2JSKNT.yaml
hrpsys_gazebo_tutorials/config/HRP2JSKNTS.yaml
hrpsys_gazebo_tutorials/config/HRP2JSKNTS_indigo.yaml
hrpsys_gazebo_tutorials/config/HRP2JSKNT_indigo.yaml
hrpsys_gazebo_tutorials/config/HRP2JSK_indigo.yaml
hrpsys_gazebo_tutorials/config/SampleRobot_indigo.yaml
hrpsys_gazebo_tutorials/launch/gazebo_hrp2jsk_no_controllers_indigo.launch
hrpsys_gazebo_tutorials/launch/gazebo_hrp2jsknt_no_controllers_indigo.launch
hrpsys_gazebo_tutorials/launch/gazebo_hrp2jsknts_no_controllers_indigo.launch
hrpsys_gazebo_tutorials/launch/gazebo_samplerobot_no_controllers_indigo.launch
hrpsys_gazebo_tutorials/launch/hrp2jsk_hrpsys_bringup.launch
hrpsys_gazebo_tutorials/launch/hrp2jsknt_hrpsys_bringup.launch
hrpsys_gazebo_tutorials/launch/hrp2jsknts_hrpsys_bringup.launch
hrpsys_gazebo_tutorials/launch/samplerobot_hrpsys_bringup.launch
hrpsys_gazebo_tutorials/robot_models/HRP2JSK/HRP2JSK.urdf.xacro
hrpsys_gazebo_tutorials/robot_models/HRP2JSKNT/HRP2JSKNT.urdf.xacro
hrpsys_gazebo_tutorials/robot_models/HRP2JSKNTS/HRP2JSKNTS.urdf.xacro
hrpsys_gazebo_tutorials/robot_models/SampleRobot/SampleRobot.urdf.xacro
hrpsys_ros_bridge_tutorials/models/hrp2jsk.yaml
hrpsys_ros_bridge_tutorials/models/hrp2jsknt.yaml
hrpsys_ros_bridge_tutorials/models/hrp2jsknts.yaml
hrpsys_ros_bridge_tutorials/models/samplerobot.yaml

This PR enables hrp2 gazebo simulation on `kinetic`.
This PR in on https://github.com/start-jsk/rtmros_gazebo/pull/236.
```
roslaunch hrpsys_gazebo_tutorials gazebo_hrp2jsk_no_controllers.launch
rtmlaunch hrpsys_gazebo_tutorials hrp2jsk_hrpsys_bringup.launch 
```
```
roslaunch hrpsys_gazebo_tutorials gazebo_hrp2jsknt_no_controllers.launch
rtmlaunch hrpsys_gazebo_tutorials hrp2jsknt_hrpsys_bringup.launch 
```
```
roslaunch hrpsys_gazebo_tutorials gazebo_hrp2jsknts_no_controllers.launch
rtmlaunch hrpsys_gazebo_tutorials hrp2jsknts_hrpsys_bringup.launch 
```

[on #250 of start-jsk/rtmros_gazebo][hrpsys_gazebo_tutorials] enable samplerobot and hrp2 on kinetic and melodic

---

.travis.rosinstall.melodic
.travis.yml

This PR includes https://github.com/start-jsk/rtmros_tutorials/pull/567, https://github.com/start-jsk/rtmros_tutorials/pull/570.

[on #249 of start-jsk/rtmros_gazebo]Add melodic test

---

hrpsys_ros_bridge_tutorials/CMakeLists.txt

SampleRobotとHRP2JSK*の`.conf`ファイルに，`pdgains.file_name`を追加するPull Requestです．
これまでは`RobotHardware.conf`ファイルにしか`pdgains.file_name`が書かれていなかったのですが，choreonoidでのシミュレーション時に不具合があったため，
[JAXON_JVRC](https://github.com/start-jsk/rtmros_choreonoid/blob/bc303068b04ba35d594a0196085bea9a34363fb7/hrpsys_choreonoid_tutorials/CMakeLists.txt#L86)にあわせて`.conf`ファイルにも書くようにしました．

[hrpsys_ros_bridge_tutorials/CMakeLists.txt] add pdgains.file_name to conf-file (SampleRobot and HRP2JSK*)

---

hrpsys_ros_bridge_tutorials/src/hrpsys_ros_bridge_tutorials/urata_hrpsys_config.py

#599 について最終的にどの様な方法とするかは議論の必要があるかと思いますが、当面の措置として方法3にのっとりオフセット値の設定を削除しました。対応を長らく忘れており大変申し訳ありません。@kindsenior

[hrpsys_ros_bridge_tutorials][JAXON_RED] remove kfp.sensorRPY_offset

---

.github/workflows/indigo.yml
.github/workflows/kinetic.yml
.github/workflows/melodic.yml

Indigo test fails with `Error: EACCES: permission denied`:
https://github.com/start-jsk/rtmros_tutorials/actions/runs/3736972571/jobs/6341782989
~~We need https://github.com/jsk-ros-pkg/jsk_travis/pull/437 to pass indigo check??~~
It seems that what we really need is something like https://github.com/jsk-ros-pkg/jsk_robot/pull/1643.
Updating jsk_travis is optional, but probably recommended.

[CI] Update jsk_travis to 0.5.25 & update checkout to avoid permission error

---

hironx_tutorial/config/hironxjsk_image_transport_plugins_params.yaml
hironx_tutorial/launch/hironxjsk_real.launch

Previously, only `/head_camera/depth/image_raw/compressedDepth` can be subscribed without hz drop for `rosbag record`, but nodes on remote PC may want to subscribe other `compressedDepth` topics.
The implementation is based on https://github.com/jsk-ros-pkg/jsk_robot/pull/1493
cc. @Affonso-Gui

[hironx_tutorial][HIRONXJSK] Enable to subscribe all compressedDepth without hz drop

---

hrpsys_ros_bridge_tutorials/euslisp/hironxjsk-utils.l

Currently, `:self-collision-check` on HIRONXJSK always returns non-`nil` value:
```
1.irteusgl$ (hironxjsk-init)
...
2.irteusgl$ (objects (list *hironxjsk*))
;; (make-irtviewer) executed
(#<hironxjsk-sensor-robot #X5582026b6f80 HIRONXJSK  0.0 0.0 0.0 / 0.0 0.0 0.0>)
3.irteusgl$ (send *hironxjsk* :reset-manip-pose)
#f(-0.6 0.0 -100.0 15.2 9.4 3.2 0.6 0.0 -100.0 -15.2 9.4 -3.2 0.0 0.0 0.0)
4.irteusgl$ (send *hironxjsk* :self-collision-check)
((#<bodyset-link #X5582027886c0 CHEST_JOINT0_Link  0.0 0.0 0.0 / 0.0 0.0 0.0> . #<bodyset-link #X5582029ec050 HEAD_JOINT1_Link  0.0 0.0 569.5 / 0.0 0.0 0.0>))
```
This is because ~~convex hull of~~ `CHEST_JOINT0_Link` and `HEAD_JOINT1_Link` always collide:
```
18.irteusgl$ (send-all (remove nil (mapcar #'(lambda (l) (let ((name (send l :name))) (if (or …
```

[hrpsys_ros_bridge_tutorials][HIRONXJSK] Enable :self-collision-check on euslisp interface

---

hironx_tutorial/config/hironxjsk_image_transport_plugins_params.yaml
hironx_tutorial/launch/hironxjsk_real.launch

HIRO頭部のprime senseカメラにおいて、点群の三次元位置情報と色情報がずれていたり、RGB画像とdepth画像の位置情報がずれているといった問題があったので、openni2.launch(https://github.com/ros-drivers/openni2_launch/blob/797cc0b4b765e0701ad8b33872c530732d9d0b23/launch/openni2.launch#L27 )のdepth_registrationの値をfalseからtrueへ変更しました。
（変更前）
（変更後）
変更後は机の端の点群がより合う（変更前は床面の黒色が変更後よりずれて表れてしまっている）ようになりました。

[hironx_tutorial]change depth_registration value from false to true to fix the gap between XYZ and color
